#!/usr/bin/env bash
# Generated by neil-bootstrap-skill
set -u

cd "$(dirname "$0")"
LOG="./server_bootstrap.log"
: > "$LOG"   # truncate previous run's log

READY_TIMEOUT=180   # seconds per service

# SSH隧道配置
RDS_HOST="rm-t4n0j5pc1qubb12l0.mysql.singapore.rds.aliyuncs.com"
ECS_HOST="43.106.17.115"
SSH_KEY=".deploy_key"
LOCAL_DB_PORT=3306

log() { echo "$@" | tee -a "$LOG"; }

free_port() {
  local port="$1"
  local pids
  pids=$(lsof -ti:"$port" 2>/dev/null || true)
  if [ -n "$pids" ]; then
    log "[port $port] occupied by pids: $pids, killing..."
    # shellcheck disable=SC2086
    kill -9 $pids 2>/dev/null || true
    sleep 1
  fi
}

probe_port() {
  local port="$1"
  nc -z 127.0.0.1 "$port" 2>/dev/null || nc -z ::1 "$port" 2>/dev/null
}

wait_ready() {
  local name="$1" port="$2" pid="$3"
  local i
  for i in $(seq 1 "$READY_TIMEOUT"); do
    if probe_port "$port"; then
      log "✓ $name ready  http://localhost:$port  (pid=$pid)  after ${i}s"
      return 0
    fi
    if ! kill -0 "$pid" 2>/dev/null; then
      log "✗ $name process exited before becoming ready (pid=$pid)"
      log "---- last 30 lines of $LOG ----"
      tail -n 30 "$LOG"
      return 1
    fi
    sleep 1
  done
  log "✗ $name did not become ready within ${READY_TIMEOUT}s"
  log "---- last 30 lines of $LOG ----"
  tail -n 30 "$LOG"
  return 1
}

# ============================================================
# Step 1: 加载环境变量
# ============================================================
if [ -f .env ]; then
  log "[env] loading .env"
  set -a; source .env; set +a
else
  log "✗ .env not found. Copy from deploy/.env.template and fill in values."
  exit 1
fi

# 校验必需变量
for var in DB_USERNAME DB_PASSWORD; do
  if [ -z "${!var:-}" ]; then
    log "✗ env $var is required but not set. Aborting."
    exit 1
  fi
done

# ============================================================
# Step 2: SSH隧道（本地 → ECS → RDS内网）
# ============================================================
log "[tunnel] checking SSH tunnel to RDS..."

# 清理已有的隧道
pkill -f "ssh.*${LOCAL_DB_PORT}.*${ECS_HOST}" 2>/dev/null || true
sleep 1

if [ ! -f "$SSH_KEY" ]; then
  log "✗ SSH key not found: $SSH_KEY"
  exit 1
fi

ssh -fN \
  -L ${LOCAL_DB_PORT}:${RDS_HOST}:3306 \
  root@${ECS_HOST} \
  -i "$SSH_KEY" \
  -o StrictHostKeyChecking=no \
  -o ConnectTimeout=20 \
  -o ServerAliveInterval=30 \
  -o ServerAliveCountMax=3 \
  >> "$LOG" 2>&1

if [ $? -ne 0 ]; then
  log "✗ SSH tunnel failed to establish. Check network and .deploy_key."
  exit 1
fi

# 等待隧道就绪
sleep 2
if probe_port "$LOCAL_DB_PORT"; then
  log "✓ SSH tunnel ready (localhost:${LOCAL_DB_PORT} → RDS)"
else
  log "✗ SSH tunnel port $LOCAL_DB_PORT not responding"
  exit 1
fi

# ============================================================
# Step 3: 启动 Spring Boot (distributor-server)
# ============================================================
free_port 8080
log "[server] starting distributor-server..."

nohup mvn spring-boot:run -pl distributor-server >> "$LOG" 2>&1 &
SERVER_PID=$!

wait_ready "distributor-server" 8080 "$SERVER_PID" || exit 1

log ""
log "All services started. Logs: $LOG"
log "  SSH Tunnel:  localhost:${LOCAL_DB_PORT} → ${RDS_HOST}:3306"
log "  Server:      http://localhost:8080"
log "  Health:      http://localhost:8080/actuator/health"
