#!/usr/bin/env bash
# Generated by neil-bootstrap-skill
cd "$(dirname "$0")"

# Spring Boot server
PORTS=( 8080 )

# Kill SSH tunnel to RDS
echo "[tunnel] killing SSH tunnel..."
pkill -f "ssh.*3306.*43.106" 2>/dev/null && echo "[tunnel] killed" || echo "[tunnel] already stopped"

# Kill server by port
for port in "${PORTS[@]}"; do
  pids=$(lsof -ti:"$port" 2>/dev/null || true)
  if [ -n "$pids" ]; then
    echo "[port $port] killing pids: $pids"
    # shellcheck disable=SC2086
    kill -9 $pids 2>/dev/null || true
  else
    echo "[port $port] already free"
  fi
done

exit 0
